# Generated by Django 5.0.3 on 2024-08-05 16:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('name', models.CharField(max_length=100)),
                ('registration_number', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('student_class', models.CharField(max_length=50)),
                ('year_of_admission', models.PositiveIntegerField()),
                ('provisional_exam_results', models.DecimalField(decimal_places=2, max_digits=5)),
                ('cat_results', models.DecimalField(decimal_places=2, max_digits=5)),
                ('year_of_registration', models.PositiveIntegerField()),
                ('pin', models.CharField(max_length=128)),
                ('parent_names', models.CharField(max_length=200)),
                ('parent_phone_number', models.CharField(max_length=20)),
                ('county_of_residence', models.CharField(max_length=100)),
                ('country_of_residence', models.CharField(max_length=100)),
                ('student_photo', models.ImageField(upload_to='student_photos/')),
                ('date_of_birth', models.DateField()),
                ('expected_year_of_completion', models.PositiveIntegerField()),
                ('discipline_score', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('discipline_cases', models.TextField()),
                ('fee_arrears', models.DecimalField(decimal_places=2, max_digits=10)),
                ('hostel_number', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
